/**
 * Curated speakable league-code vocabulary (100 + 100).
 * Codes are ADJECTIVE + NOUN (e.g. CLUTCHSTRIKER), uppercase, no separator.
 */

export const LEAGUE_ADJECTIVES: readonly string[] = [
  "CLUTCH", "SWIFT", "BOLD", "SHARP", "RAPID", "STEELY", "FIERCE", "CALM",
  "SLICK", "BRAVE", "CRISP", "GRITTY", "NIMBLE", "PROUD", "SOLID", "VIVID",
  "KEEN", "LUCKY", "MIGHTY", "NOBLE", "PRIME", "QUICK", "ROYAL", "STOUT",
  "TOUGH", "ULTRA", "VITAL", "WISE", "ACUTE", "BRISK", "CLEAN", "CLEVER",
  "ELITE", "FLASH", "GRAND", "HARDY", "IVORY", "JOLLY", "LUCID", "MAJOR",
  "NIFTY", "OPAL", "PLUCKY", "QUARTZ", "READY", "SILVER", "TIDAL", "URBAN",
  "VALOR", "WILD", "XENON", "YOUNG", "ZESTY", "ACTIVE", "BLAZING", "COSMIC",
  "DYNAMIC", "ELECTRIC", "FLYING", "GOLDEN", "HEROIC", "IRON", "JADED",
  "KINETIC", "LEGEND", "MAGNET", "NITRO", "ORBIT", "PEAK", "QUANTUM",
  "RISING", "SONIC", "TURBO", "UNITED", "VORTEX", "WARRIOR", "XTREME",
  "YELLOW", "ZENITH", "ALPINE", "BRONZE", "CRIMSON", "DESERT", "EMERALD",
  "FROZEN", "GALAXY", "HARBOUR", "IMPACT", "JUNGLE", "KNIGHT", "LUNAR",
  "MARINE", "NEON", "OCEAN", "PHOENIX", "RADIANT", "STADIUM", "THUNDER",
  "ARCTIC", "BLAZE", "CARBON", "DELTA",
];

export const LEAGUE_NOUNS: readonly string[] = [
  "STRIKER", "PUNTER", "CAPTAIN", "KEEPER", "WINGER", "FINISHER", "TACKLER",
  "SCRUM", "FLYHALF", "HOOKER", "LOCK", "FLANKER", "NUMBER8", "FULLBACK",
  "MIDFIELD", "FORWARD", "DEFENDER", "PLAYMAKER", "SNIPER", "MARKSMAN",
  "COACH", "MANAGER", "REFEREE", "LINEOUT", "TRYLINE", "TOUCHLINE", "POST",
  "CROSSBAR", "CORNER", "PENALTY", "FREEKICK", "OFFSIDE", "HATTRICK",
  "CLEANSHT", "ASSIST", "VOLLEY", "HEADER", "DRIBBLE", "THROUGH", "OVERLAP",
  "COUNTER", "PRESS", "SWEEPER", "LIBERO", "ANCHOR", "MAESTRO", "VIRTUOSO",
  "ACE", "CHAMPION", "CONTENDER", "RIVAL", "DERBY", "CLASSIC", "FINAL",
  "SEMI", "QUARTER", "GROUP", "POOL", "TABLE", "LADDER", "PODIUM", "MEDAL",
  "TROPHY", "CUP", "SHIELD", "BOOT", "STUD", "WHISTLE", "FLAG", "VARREF",
  "STADIUM", "ARENA", "PITCH", "FIELD", "TURF", "GRASS", "TERRACE", "STAND",
  "CROWD", "ULTRAS", "BANNER", "CHANT", "ANTHEM", "KICKOFF", "HALFTIME",
  "INJURY", "SUB", "BENCH", "SQUAD", "ROSTER", "LINEUP", "FORMATION", "FIRSTXI",
  "PACK", "BACKLINE", "FRONTROW", "LOOSE", "TIGHT", "MAUL", "RUCK", "SCRUM5",
  "DROPGOAL", "CONVERT", "TOUCH", "BREAK",
];
