-- Alias of 20260801160000_create_system_metrics.sql for discoverability.
-- Prefer the timestamped migration for apply order.

-- API health metrics for Admin dashboard (sync-schedule / sync-live).

CREATE TABLE IF NOT EXISTS public.system_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'STABLE'
    CHECK (status IN ('STABLE', 'ERROR')),
  last_sync_time timestamptz NULL,
  api_quota_remaining integer NULL,
  error_message text NULL,
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

COMMENT ON TABLE public.system_metrics IS
  'Edge sync health rows (Football/Rugby schedule + live). Upserted by sync functions.';

ALTER TABLE public.system_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS system_metrics_admin_select ON public.system_metrics;
CREATE POLICY system_metrics_admin_select
  ON public.system_metrics
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = (auth.uid())::text
        AND COALESCE(p.is_admin, false) = true
    )
  );

INSERT INTO public.system_metrics (service_name, status)
VALUES
  ('Football Schedule Sync', 'STABLE'),
  ('Football Live Sync', 'STABLE'),
  ('Rugby Schedule Sync', 'STABLE'),
  ('Rugby Live Sync', 'STABLE')
ON CONFLICT (service_name) DO NOTHING;

-- Ensure new European leagues exist in competitions catalog.
INSERT INTO public.competitions (id, api_sports_id, sport, name, country)
VALUES
  ('f-laliga', 140, 'football', 'La Liga', 'Spain'),
  ('f-bundesliga', 78, 'football', 'Bundesliga', 'Germany'),
  ('f-ligue1', 61, 'football', 'Ligue 1', 'France')
ON CONFLICT (id) DO UPDATE
SET
  api_sports_id = EXCLUDED.api_sports_id,
  name = EXCLUDED.name,
  sport = EXCLUDED.sport,
  country = EXCLUDED.country,
  updated_at = timezone('utc', now());

UPDATE public.competitions
SET name = 'FA Community Shield', api_sports_id = 528, updated_at = timezone('utc', now())
WHERE id = 'f-shield';

UPDATE public.competitions
SET name = 'English Premier League', updated_at = timezone('utc', now())
WHERE id = 'f-epl';

UPDATE public.competitions
SET name = 'Scottish Premiership', updated_at = timezone('utc', now())
WHERE id = 'f-spfl';

UPDATE public.competitions
SET name = 'EFL Championship', updated_at = timezone('utc', now())
WHERE id = 'f-championship';
